version: '3.8'

services:
  # Movie Vibes Application
  movievibes:
    build: .
    container_name: movievibes-app
    ports:
      - "8080:8080"
    environment:
      # Spring profiles
      - SPRING_PROFILES_ACTIVE=docker
      # Ollama connection (assuming Ollama runs on host)
      - SPRING_AI_OLLAMA_BASE_URL=http://host.docker.internal:11434
      - SPRING_AI_OLLAMA_MODEL=llama3
      # OMDb API configuration
      - OMDB_URL=https://www.omdbapi.com/
      - OMDB_API_KEY=${OMDB_API_KEY:-your_omdb_api_key_here}
    depends_on:
      - ollama
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Ollama for local AI model
  ollama:
    image: ollama/ollama:latest
    container_name: movievibes-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # Pull llama3 model on startup
    command: >
      sh -c "
        ollama serve &
        sleep 10 &&
        ollama pull llama3 &&
        wait
      "

volumes:
  ollama_data:
    driver: local
